- name: Check services emqx is enabled
  ansible.builtin.service:
    name: emqx
    enabled: yes
- name: Check services nginx is enabled
  ansible.builtin.service:
    name: nginx
    enabled: yes
- name: Check services elasticsearch.service is enabled
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
- name: Check services tidb is enabled
  ansible.builtin.service:
    name: tidb
    enabled: yes